version: '3'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    container_name: book-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/config/nginx/local.conf:/etc/nginx/conf.d/local.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ssl:/etc/nginx/ssl
      - ./public_html:/usr/share/nginx/html
    depends_on:
      - php-fpm
      - postgres
      - redis
    networks:
      - book-network

  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-php-fpm
    container_name: book-php-fpm
    volumes:
      - ./docker/config/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./public_html:/usr/share/nginx/html
    networks:
      - book-network

  php-cli:
    build:
      context: ./docker
      dockerfile: Dockerfile-php-cli
    container_name: book-php-cli
    volumes:
      - ./public_html:/usr/share/nginx/html
    tty: true
    networks:
      - book-network

  postgres:
    image: postgres:14.2
    container_name: book-postgres
    #!!!
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: book
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - book-network

  redis:
    image: redis:6.2.6
    container_name: book-redis
    env_file:
      - .env
    command: redis-server --requirepass ${redis_password}
    networks:
      - book-network

networks:
  book-network:
    driver: bridge